name: Tests (arm64)

on:
  push:
  pull_request:

jobs:
  test:
    name: Test arm64 (${{ matrix.compiler }})
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 120

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc
          - clang

    container: debian:sid

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            ca-certificates \
            git \
            make \
            gcc \
            clang \
            libclang-rt-dev \
            meson \
            ninja-build \
            cmake \
            pkg-config \
            libcriterion-dev \
            libgpg-error-dev \
            libzstd-dev

      - name: Checkout repository
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd "${GITHUB_WORKSPACE}"

          git init
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          git remote add origin \
            "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

          git fetch --depth=1 origin "${GITHUB_SHA}"
          git checkout --detach "${GITHUB_SHA}"

          git submodule update --init --recursive

      - name: Show compiler version
        env:
          CC: ${{ matrix.compiler }}
        run: |
          uname -m
          $CC --version

      - name: Test
        env:
          CC: ${{ matrix.compiler }}
        run: ASAN_OPTIONS=detect_leaks=0 make test EXTRA_CFLAGS='-fsanitize=address,undefined'
